### ISSUE TITLE
Rename `Result` to something else due to conflicts

### ISSUE THREAD

**Issue by michaelbukachi** [droidconKE/droidconKE2019App#57]
@wangerekaharun It seems that `Result` is an inbuilt class in kotlin which should rename to something else to prevent conflicts.

**Comment by wangerekaharun** [comment]
Noted. Will Rename.

**Comment by johnGachihi** [comment]
It appears to me that FirebaseResult has been re-renamed back to Result in the repository classes (but not in the viewmodels). This happens in this commit fa814945a54ff26cb342501018ef261e8451ffd1

**Comment by michaelbukachi** [comment]
@johnGachihi. Do you mind opening a pull request?
