### ISSUE TITLE
Code seems broken due to re-renaming of FirebaseResult back to Result in the repository classes only

### ISSUE THREAD

**Issue by johnGachihi** [droidconKE/droidconKE2019App#63]
Initially the sealed class Result was renamed to FirebaseResult (in ad33d2e5abae5ed48b3c4b17684371882accd1a8). Later, (maybe because a pull request wasn't merged well) FirebaseResult was renamed back to Result but only in the repository classes (in this commit: fa814945a54ff26cb342501018ef261e8451ffd1).
Therefore, almost all viewmodels have 'incompatible types' errors because they expect a FirebaseResult but get Result returned from the repository methods. (e.g https://github.com/droidconKE/droidconKE2019App/blob/337fcc113cfd18af47ee0f01379bbc0bb8a78694/app/src/main/java/com/android254/droidconke19/viewmodels/AboutViewModel.kt#L36)

Also, the develop branch is behind master.

**Comment by wangerekaharun** [comment]
@johnGachihi  Why did you close this? We are still looking into this.

**Comment by johnGachihi** [comment]
@wangerekaharun A pull request with the correction was merged into the develop branch

**Comment by michaelbukachi** [comment]
@johnGachihi Let project maintainers close an issue. Also, a merge request doesn't always mean that the issue has been closed.

**Comment by johnGachihi** [comment]
> @johnGachihi Let project maintainers close an issue. Also, a merge request doesn't always mean that the issue has been closed.

Understood.

**Comment by wangerekaharun** [comment]
Fixed the issue to on Master. Also Note that master might be behind develop at times as we do end-to-end testing on our side too
