### ISSUE TITLE
Remove NonNullable LiveData classes

### ISSUE THREAD

**Issue by michaelbukachi** [droidconKE/droidconKE2019App#66]
We should remove all NonNull LiveData classes and replace them with the basic counterparts since null checks are already done.

**Comment by wangerekaharun** [comment]
@michaelbukachi removed all NonNull LiveData classes. Cross check the develop branch

**Comment by michaelbukachi** [comment]
Awesome. Will do in the morning.

**Comment by michaelbukachi** [comment]
It's good. Let's wait for issue #65 before merging to master.

**Comment by michaelbukachi** [comment]
I've merged the the pull request.

**Comment by wangerekaharun** [comment]
Okay merging to master and closing this.
