### ISSUE TITLE
Resolve Gradle Conflicts

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE2019App#67]
Remove Double Declarations of dependencies and Resolve Conflicts on Master Branch

**Comment by wangerekaharun** [comment]
@chepsi check whether the Gradle conflicts has been resolved by pulling the latest changes  on both master and develop branch

**Comment by ghost** [comment]
@wangerekaharun the issue has been resolved.

**Comment by wangerekaharun** [comment]
Okay. Closing the Issue now
