### ISSUE TITLE
Fix broken tests

### ISSUE THREAD

**Issue by michaelbukachi** [droidconKE/droidconKE2019App#74]
It seems we've been having broken tests for quite a number of commits. Let me take this up.

**Comment by wangerekaharun** [comment]
Must be because of the Refactors when Removing the multiple Livedata definitions.. Forgot to check the tests too

**Comment by wangerekaharun** [comment]
On the [Latest Commit](https://github.com/droidconKE/droidconKE2019App/commit/88f59e2af1ff362e4cb3cd56d115ae35a18a339e) Commented out some tests on the EventTypeViewModelTest, might be worth also looking and adjusting where necessary.

**Comment by michaelbukachi** [comment]
I've resolved this issue. Forgot to reference it.
